# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Ownership
title: Patrick Henson
author: Patrick Henson
email: contact@patrickhenson.com
description: >- # this means to ignore newlines until "baseurl:"
  A blog dedicated to software engineering, personal projects, and useful resources. 

# Site info
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://patrickhenson.com" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: UA-119933231-1
lang: en

# Social links
social:
  links:
    - https://linkedin.com/in/patrickhenson
    - https://github.com/patrickhenson

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Customize navigation items displayed in the header
header_pages:
  - about.md

header_links:
  - title: "LinkedIn"
    url: https://linkedin.com/in/patrickhenson
  - title: "GitHub"
    url: https://github.com/patrickhenson

# Determine if the feed displays the contents of the post below the title and date.
show_excerpts: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
